/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0iUIicQnxFy
 */
import { Input } from "@/components/ui/input"
import { Button } from "./ui/button"

export function AgregarExpediente() {
  return (
    <div key="1" className="bg-white p-4 shadow-md">
      <div className="shadow-lg border border-gray-200 p-4 my-2">
        <h1 className="text-lg font-bold mb-2">CREAR EXPEDIENTE</h1>
        <div className="grid grid-cols-1 gap-2 mb-2">
          <div>
            <label className="block text-sm font-medium mb-1">Expediente N°:</label>
            <Input className="bg-gray-100 p-2" defaultValue="08116-2012-0-1801-JP-LA-03" />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Proceso:</label>
            <Input className="bg-gray-100 p-2" defaultValue="ABREVIADO" />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Fecha de Inicio:</label>
            <Input className="bg-gray-100 p-2" defaultValue="15/12/2021" />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Especialidad:</label>
            <Input className="bg-gray-100 p-2" defaultValue="LABORAL" />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Observación:</label>
            <Input
              className="bg-gray-100 p-2"
              defaultValue="ADJ. TICKET ATENCION N° 959049/ANEXO(S) A LA-1J COPIAS SIMPLES"
            />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Estado:</label>
            <Input className="bg-gray-100 p-2" defaultValue="EN EJECUCION" />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Material(es):</label>
            <Input
              className="bg-gray-100 p-2"
              defaultValue="PAGO DE BENEFICIOS SOCIALES Y/O INDEMNIZACION U OTROS BENEFICIOS ECONOMICOS"
            />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Fecha Conclusión:</label>
            <Input className="bg-gray-100 p-2" defaultValue="----" />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Etapa Procesal:</label>
            <Input className="bg-gray-100 p-2" defaultValue="GENERAL" />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Motivo Conclusión:</label>
            <Input className="bg-gray-100 p-2" defaultValue="------" />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Sumilla:</label>
            <Input className="bg-gray-100 p-2" defaultValue="DDA. PAGO DE REMUNERACIONES" />
          </div>
        </div>
      </div>
      <div className="shadow-lg border border-gray-200 p-4 my-2">
        <h2 className="text-lg font-semibold mb-2">PARTES PROCESALES</h2>
        <div className="mb-2">
          <div className="grid grid-cols-1 gap-2 mb-2">
            <div>
              <label className="block text-sm font-medium mb-1">Apellido Paterno / Razón Social:</label>
              <Input className="bg-gray-100 p-2" defaultValue="---" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Apellido Materno:</label>
              <Input className="bg-gray-100 p-2" defaultValue="---" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Nombres:</label>
              <Input className="bg-gray-100 p-2" defaultValue="---" />
            </div>
          </div>
        </div>
      </div>
      <div className="shadow-lg border border-gray-200 p-4 my-2">
        <h2 className="text-lg font-semibold mb-2">SEGUIMIENTO DEL EXPEDIENTE</h2>
        <div className="flex justify-between items-center mb-2" />
        <div className="mb-2">
          <div className="grid grid-cols-1 gap-2 mb-2">
            <div>
              <label className="block text-sm font-medium mb-1">Fecha de Ingreso:</label>
              <Input className="bg-gray-100 p-2" defaultValue="18/04/2024 16:22" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Acto:</label>
              <Input className="bg-gray-100 p-2" defaultValue="INFORME" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Folios:</label>
              <Input className="bg-gray-100 p-2" defaultValue="6" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Proveido:</label>
              <Input className="bg-gray-100 p-2" defaultValue="No Proveido" />
            </div>
          </div>
          <Input
            className="bg-gray-100 p-2"
            defaultValue="ADULTA MAYOR Y DIABETICA SOLICITA DECLARAR INFUNDADA OPOSICION DILATORIA DE NAVARRETE Y SE GENERE LA ORDEN DE PAGO DE DEPOSITO JUDICIAL ELECTRONICO A FAVOR DE LA DEMANDANTE"
          />
        </div>
        <div className="mb-2">
          <label className="block text-sm font-medium mb-1">Descripción de Usuario:</label>
          <Input className="bg-gray-100 p-2" defaultValue="INGRESADO POR:USUARIO DE MESAS PARTES WEB" />
        </div>
      </div>
      <Button>Agregar expediente</Button>

    </div>
  )
}
