/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CYoCcLULPWg
 */
import Link from "next/link"

export function Dashboard() {

  
  return (
    <>
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <nav className="flex-col hidden gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 lg:gap-6">
          <Link className="flex items-center gap-2 text-lg font-semibold md:text-base" href="/dashboard">
            <GavelIcon className="w-6 h-6 text-[#0FB79D]" />
            <span className="sr-only">Segumipol</span>
          </Link>
          <Link className="font-bold" href="/dashboard">
            Segumipol
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="/dashboard/abogados">
            Abogados
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="/dashboard/clientes">
            Clientes
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="/dashboard/expedientes">
            Expedientes
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="/dashboard-client/perfil">
            Mi perfil
          </Link>
        </nav>
      </header>
     
    </>
  )
}


function GavelIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m14 13-7.5 7.5c-.83.83-2.17.83-3 0 0 0 0 0 0 0a2.12 2.12 0 0 1 0-3L11 10" />
      <path d="m16 16 6-6" />
      <path d="m8 8 6-6" />
      <path d="m9 7 8 8" />
      <path d="m21 11-8-8" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}


function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  )
}
