/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4pHVEW74cQC
 */
import { Button } from "@/components/ui/button"

export function Header() {
  return (
    <div className="flex flex-col h-screen justify-between">
      <main />
      <footer className="flex items-center justify-between p-4 bg-gray-900 text-white">
        <Button size="icon" variant="ghost">
          <ArrowLeftIcon className="h-6 w-6" />
          <span className="sr-only">Back</span>
        </Button>
        <Button size="icon" variant="ghost">
          <HomeIcon className="h-6 w-6" />
          <span className="sr-only">Home</span>
        </Button>
        <Button size="icon" variant="ghost">
          <UserIcon className="h-6 w-6" />
          <span className="sr-only">Profile</span>
        </Button>
      </footer>
    </div>
  )
}


function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
