/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5Gg8bPX6iVx
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"

export function MiPerfil() {
  return (
    <main className="flex flex-col items-center justify-center min-h-screen bg-gray-100 p-4">
      <div className="w-full max-w-md mx-auto">
        <Card className="w-full">
          <CardHeader>
            <CardTitle>Perfil</CardTitle>
            <CardDescription>Información de tu perfil.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="nombre">Nombre</Label>
              <p className="text-gray-700 " id="nombre">
                Cynthia
              </p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="apellido">Apellido</Label>
              <p className="text-gray-700" id="apellido">
                Segumipol
              </p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="cip">N° Cip</Label>
              <p className="text-gray-700" id="cip">
                12345678
              </p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <p className="text-gray-700" id="email">
               Cynthia@Segumipol.com
              </p>
            </div>
          </CardContent>
          <CardFooter className="flex flex-row gap-2">
            <Button className="w-full">Cambiar Password</Button>
            <Button className="w-full">Cambiar Datos</Button>
          </CardFooter>
        </Card>
      </div>
    </main>
  )
}
