/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/JBkDFHxtuC7
 */


export function MisExpedientes() {
  return (
    <div key="1" className="bg-gray-100 p-8 shadow-md">
      <h2 className="text-2xl text-center font-bold mb-4">Mis expedientes</h2>
      <div className="shadow-lg border border-gray-200 p-4 my-2 bg-gray-50">
        <h1 className="text-lg font-bold mb-2">REPORTE DE EXPEDIENTE</h1>
        <div className="grid grid-cols-1 gap-2 mb-2">
          <div>
            <label className="block text-sm font-medium mb-1">Expediente N°:</label>
            <p className="bg-gray-100 p-2">08116-2012-0-1801-JP-LA-03</p>
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Proceso:</label>
            <p className="bg-gray-100 p-2">ABREVIADO</p>
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Fecha de Inicio:</label>
            <p className="bg-gray-100 p-2">15/12/2021</p>
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Especialidad:</label>
            <p className="bg-gray-100 p-2">LABORAL</p>
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Observación:</label>
            <p className="bg-gray-100 p-2">ADJ. TICKET ATENCION N° 959049/ANEXO(S) A LA-1J COPIAS SIMPLES</p>
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Estado:</label>
            <p className="bg-gray-100 p-2">EN EJECUCION</p>
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Material(es):</label>
            <p className="bg-gray-100 p-2">
              PAGO DE BENEFICIOS SOCIALES Y/O INDEMNIZACION U OTROS BENEFICIOS ECONOMICOS
            </p>
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Fecha Conclusión:</label>
            <p className="bg-gray-100 p-2">----</p>
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Etapa Procesal:</label>
            <p className="bg-gray-100 p-2">GENERAL</p>
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Motivo Conclusión:</label>
            <p className="bg-gray-100 p-2">------</p>
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Sumilla:</label>
            <p className="bg-gray-100 p-2">DDA. PAGO DE REMUNERACIONES</p>
          </div>
        </div>
      </div>
      <div className="shadow-lg border border-gray-200 p-4 my-2 bg-gray-50 ">
        <h2 className="text-lg font-semibold mb-2">PARTES PROCESALES</h2>
        <div className="mb-2">
          <div className="grid grid-cols-1 gap-2 mb-2">
            <div>
              <label className="block text-sm font-medium mb-1">Apellido Paterno / Razón Social:</label>
              <p className="bg-gray-100 p-2">---</p>
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Apellido Materno:</label>
              <p className="bg-gray-100 p-2">---</p>
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Nombres:</label>
              <p className="bg-gray-100 p-2">---</p>
            </div>
          </div>
        </div>
      </div>
      <div className="shadow-lg border border-gray-200 p-4 my-2 bg-gray-50">
        <h2 className="text-lg font-semibold mb-2">SEGUIMIENTO DEL EXPEDIENTE</h2>
        <div className="flex justify-between items-center mb-2" />
        <div className="mb-2">
          <div className="grid grid-cols-1 gap-2 mb-2">
            <div>
              <label className="block text-sm font-medium mb-1">Fecha de Ingreso:</label>
              <p className="bg-gray-100 p-2">18/04/2024 16:22</p>
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Acto:</label>
              <p className="bg-gray-100 p-2">INFORME</p>
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Folios:</label>
              <p className="bg-gray-100 p-2">6</p>
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Proveido:</label>
              <p className="bg-gray-100 p-2">No Proveido</p>
            </div>
          </div>
          <p className="bg-gray-100 p-2">
            ADULTA MAYOR Y DIABETICA SOLICITA DECLARAR INFUNDADA OPOSICION DILATORIA DE NAVARRETE Y SE GENERE LA ORDEN
            DE PAGO DE DEPOSITO JUDICIAL ELECTRONICO A FAVOR DE LA DEMANDANTE
          </p>
        </div>
        <div className="mb-2">
          <label className="block text-sm font-medium mb-1">Descripción de Usuario:</label>
          <p className="bg-gray-100 p-2">INGRESADO POR:USUARIO DE MESAS PARTES WEB</p>
        </div>
      </div>
    </div>
  )
}
