/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/loXIUDu9PoM
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function RegistrarCuentaCliente() {
  return (
    <>
      <div className="min-h-screen bg-gray-100  flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-md w-full space-y-8">
          <div>
          <h1 className="text-3xl font-bold text-center">¡Registrese!</h1>
    <p className="text-lg text-center mt-2">Complete todos sus datos</p>
          </div>
          <form action="#" className="mt-8 space-y-6" method="POST">
            <input name="remember" type="hidden" value="true" />
            <div className="rounded-md shadow-sm -space-y-px">
              <div>
                <Label className="sr-only" htmlFor="nombre">
                  Nombre
                </Label>
                <Input
                  autoComplete="name"
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-200 border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  id="nombre"
                  name="nombre"
                  placeholder="Nombre"
                  required
                  type="text"
                />
              </div>
              <div>
                <Label className="sr-only" htmlFor="apellido">
                  Apellido
                </Label>
                <Input
                  autoComplete="family-name"
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-200  placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  id="apellido"
                  name="apellido"
                  placeholder="Apellido"
                  required
                  type="text"
                />
              </div>
              <div>
                <Label className="sr-only" htmlFor="ncip">
                  N° Cip
                </Label>
                <Input
                  autoComplete="family-name"
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-200  placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  id="ncip"
                  name="ncip"
                  placeholder="N° Cip"
                  required
                  type="number"
                />
              </div>
              <div>
                <Label className="sr-only" htmlFor="email-address">
                  Correo Electronico
                </Label>
                <Input
                  autoComplete="email"
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-200 border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  id="email-address"
                  name="email"
                  placeholder="Correo electronico"
                  required
                  type="email"
                />
              </div>
              <div>
                <Label className="sr-only" htmlFor="password">
                  Contraseña
                </Label>
                <Input
                  autoComplete="current-password"
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-200 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  id="password"
                  name="password"
                  placeholder="Contraseña"
                  required
                  type="password"
                />
              </div>
            </div>
          </form>
          <Button
            className="group relative w-full flex justify-center py-2 px-4 border border-gray-200 border-transparent text-sm font-medium rounded-md text-white bg-[#0FB79D] hover:bg-[#0FB79D]/90 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:bg-[#0FB79D]"
            type="submit"
          >
            Crear cuenta
          </Button>
        </div>
      </div>
    
    </>
  )
}
